### ISSUE TITLE
Issues Installing

### ISSUE THREAD

**Issue by jcabrerard** [stop-pre16/mcmseq#4]
Following the instructions on the README.md I come across this issue:

> devtools::install_github("stop-pre16/mcmseq", build_vignettes = T)
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials
-----------

Any ideas?

Regards,

Jorge

**Comment by stop-pre16** [comment]
Hi Jorge,

Sorry for the delay in getting you a response, but I found a resolution on a devtools github page:
https://github.com/r-lib/devtools/issues/1566

The solutions there suggests you need to unset a GITHUB_PAT in your local R environment using the command:
Sys.unsetenv("GITHUB_PAT")
and then try installing the mcmseq package.
Hopefully that works.

Thanks,
Brian

**Comment by jcabrerard** [comment]
Thank you for the response. I found the same page while researching earlier and that solution worked.

Regards,
